{
 "title": "Nginx",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Http Request Total",
   "type": "timeseries",
   "description": "Http Request Total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nginx_http_requests_total{job=\"mynginx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Up",
   "type": "gauge",
   "description": "Nginx Up",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{job=\"mynginx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Handled",
   "type": "gauge",
   "description": "Number of Connection Handled",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_connections_handled{job=\"mynginx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Accepted",
   "type": "gauge",
   "description": "Nginx Connection Accepted",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_connections_accepted{job=\"mynginx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections Writing",
   "type": "gauge",
   "description": "Number of Connections Writing",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_connections_writing{job=\"mynginx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections Active",
   "type": "gauge",
   "description": "Number of Connections Active",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_connections_active{job=\"mynginx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections Waiting",
   "type": "gauge",
   "description": "Number of Connections Waiting",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_connections_waiting{job=\"mynginx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections Reading",
   "type": "gauge",
   "description": "Number of Connections Reading",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_connections_reading{job=\"mynginx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections Waiting",
   "type": "gauge",
   "description": "Number of Connections Waiting",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_connections_waiting{job=\"mynginx\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}